name: 04 - Events

on:
    workflow_dispatch:
    issues:
        types: 
            - opened
            - assigned
    issue_comment:
        types:
            - created
    pull_request_review_comment:
        types: 
            - created
    
jobs:
    inspect-event:
        runs-on: ubuntu-24.04
        permissions:
            issues: write
        steps:
            - name: Print event details
              env:
                EVENT_NAME: ${{ github.event_name }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                COMMENT_BODY: ${{ github.event.comment.body }}
              run: |
                echo "Event Name: $EVENT_NAME"
                echo "Issue Number: $ISSUE_NUMBER"
                printf '%s\n' "$COMMENT_BODY"

            - name: Add comment as bot
              if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                GITHUB_REPOSITORY: ${{ github.repository }}
              run: |
                gh issue comment $ISSUE_NUMBER --body "Thank you for opening this issue! A team member will review it shortly." --repo $GITHUB_REPOSITORY